#!/usr/bin/python
import sys, os, signal
from os import path

spockd_dir = path.join(path.expanduser('~'), '.spockd')
inpipe = path.join(spockd_dir, 'inpipe')
outpipe = path.join(spockd_dir, 'outpipe')

cmd = ' '.join(sys.argv[1:])

writepipe = open(inpipe, 'w')
writepipe.write(cmd)
writepipe.close()
readpipe = open(outpipe, 'r')
returnval = readpipe.read()
readpipe.close()
print returnval
